name: Lint

on:
  pull_request:


jobs:
  golangci:
    name: 🔍 golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
          skip-go-installation: false